### PR TITLE
Make this usable after installation from npm.

### PR DESCRIPTION
**Pull request by elad**
- Add a `main` key in `package.json` so that it's usable from node.js apps
- Fix the README to use the proper package name (`anymesh` rather than `AnyMesh`)

### CODE REVIEW

**Comment by davepaul0** [comment]
looks good, thanks!

**Comment by elad** [comment]
Thanks! I should note however that I didn't get anyMesh to work at all. :( Here's my code:

``` js
var cluster = require('cluster');

if (cluster.isMaster) {
    var net = require('net');

    var num_workers = 4;
    for (var i = 0; i < num_workers; i++) {
        cluster.fork();
    }
} else {
    var anymesh = require('anymesh');

    var id = 'node-' + cluster.worker.id;
        mesh = new anymesh();

    console.log('starting', id);

    // Once connected, start sending out messages.
    mesh.connectedTo = function(info) {
        console.log(id, 'connected to:', info);

        setInterval(function() {
            var payload = {
                text: id + ' says hi!'
            };

            console.log(id, 'publishing...');
            mesh.publish('test', payload);
        }, 1000);
    }

    mesh.received = function(message) {
        console.log(id, 'received:', message);
    }

    mesh.connect(id, ['test']);
}
```

What am I doing wrong?

**Comment by davepaul0** [comment]
Hmmm... so the code you've provided, are you running this in multiple places?  Anymesh works on the idea that you have multiple Anymesh instances, whether those instances are in the same program, are running in different processes on the same network device (i.e. computer), or are running on separate network devices on the same LAN.
If you are deploying multiple any mesh instances and you're not seeing any connections, you might want to check that the any mesh instance names are different from one another.  I'm not too familiar with Cluster, so I could't say whether the worker.id you're using to assign the any mesh name is unique.

**Comment by elad** [comment]
This is a problem with cluster. There shouldn't be one because it's supposed to create separate processes as far as I understand, but I'll look into it.

**Pull request merged**
